### ISSUE TITLE
Mod prevents creation of new materials

### ISSUE THREAD

**Issue by AeoMayo** [Banane9/ResoniteStopDisappearingLocomotionMenu#1]
Somehow, and I have no idea how, since this just started after an update possibly and I'm not sure which one, but it seems like this mod breaks the new material menu. Either trying to create one thru the dev tip or material tip, or via conversion of an existing material, it's simply blank.
![image](https://github.com/Banane9/ResoniteStopDisappearingLocomotionMenu/assets/26622694/9e81d898-814b-4202-a8b1-88c34b570724)
It also straight up removes the material menu in the create new dev tip menu
![image](https://github.com/Banane9/ResoniteStopDisappearingLocomotionMenu/assets/26622694/c99f3a04-79af-4b90-8272-148d08b30b7d)

Here's a clean log where it happens.
[MA3A-6-REDUX - 2023.10.18.449 - 2023-10-19 08_04_30.log](https://github.com/Banane9/ResoniteStopDisappearingLocomotionMenu/files/13042419/MA3A-6-REDUX.-.2023.10.18.449.-.2023-10-19.08_04_30.log)
Seems line 1023 is where the stack trace is

Thank you!

**Comment by Banane9** [comment]
Did you do anything in particular to trigger this?

Other than that, the Exception you point to is a common thing with the context menu it would seem. It's something trying to drive a field that's already driven and being blocked.

**Comment by AeoMayo** [comment]
Nope. I just noticed it while working on my world. Joined another world not hosted by me and the issue persisted.
The problem disappears when I remove the mod

**Comment by AeoMayo** [comment]
Never mind. Turns out it must be a different mod because its suddenly cropped up again despite removing the mod.
Sorry for the confusion.
